// Copyright (c) 2026 100monkeys.ai
// SPDX-License-Identifier: AGPL-3.0
use std::fmt;

/// Fine-grained resource:action scopes for API key authorization.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApiScope {
    // agent
    AgentDeploy,
    AgentRead,
    AgentList,
    AgentExecute,
    AgentGenerate,
    AgentLogs,
    AgentDelete,
    // workflow
    WorkflowDeploy,
    WorkflowRead,
    WorkflowList,
    WorkflowRun,
    WorkflowValidate,
    WorkflowGenerate,
    WorkflowLogs,
    WorkflowSignal,
    WorkflowCancel,
    WorkflowDelete,
    // execution
    ExecutionRead,
    ExecutionList,
    ExecutionStream,
    ExecutionLogs,
    ExecutionCancel,
    ExecutionRemove,
    // swarm
    SwarmRead,
    SwarmList,
    SwarmCancel,
    // secret
    SecretRead,
    SecretWrite,
    SecretList,
    SecretDelete,
    SecretRotate,
    // credential
    CredentialRead,
    CredentialList,
    CredentialCreate,
    CredentialDelete,
    CredentialRotate,
    CredentialGrant,
    // approval
    ApprovalRead,
    ApprovalList,
    ApprovalApprove,
    ApprovalReject,
    // stimulus
    StimulusIngest,
    // node
    NodeRead,
    NodeList,
    NodeRegister,
    NodeDeregister,
    NodeDrain,
    NodeShutdown,
    // stack
    StackRead,
    StackUp,
    StackDown,
    StackRestart,
    StackUpdate,
    StackUninstall,
    // key (API key self-management)
    KeyRead,
    KeyList,
    KeyCreate,
    KeyRevoke,
    // tenant
    TenantRead,
    TenantList,
    TenantOnboard,
    TenantProvision,
}

impl ApiScope {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::AgentDeploy => "agent:deploy",
            Self::AgentRead => "agent:read",
            Self::AgentList => "agent:list",
            Self::AgentExecute => "agent:execute",
            Self::AgentGenerate => "agent:generate",
            Self::AgentLogs => "agent:logs",
            Self::AgentDelete => "agent:delete",
            Self::WorkflowDeploy => "workflow:deploy",
            Self::WorkflowRead => "workflow:read",
            Self::WorkflowList => "workflow:list",
            Self::WorkflowRun => "workflow:run",
            Self::WorkflowValidate => "workflow:validate",
            Self::WorkflowGenerate => "workflow:generate",
            Self::WorkflowLogs => "workflow:logs",
            Self::WorkflowSignal => "workflow:signal",
            Self::WorkflowCancel => "workflow:cancel",
            Self::WorkflowDelete => "workflow:delete",
            Self::ExecutionRead => "execution:read",
            Self::ExecutionList => "execution:list",
            Self::ExecutionStream => "execution:stream",
            Self::ExecutionLogs => "execution:logs",
            Self::ExecutionCancel => "execution:cancel",
            Self::ExecutionRemove => "execution:remove",
            Self::SwarmRead => "swarm:read",
            Self::SwarmList => "swarm:list",
            Self::SwarmCancel => "swarm:cancel",
            Self::SecretRead => "secret:read",
            Self::SecretWrite => "secret:write",
            Self::SecretList => "secret:list",
            Self::SecretDelete => "secret:delete",
            Self::SecretRotate => "secret:rotate",
            Self::CredentialRead => "credential:read",
            Self::CredentialList => "credential:list",
            Self::CredentialCreate => "credential:create",
            Self::CredentialDelete => "credential:delete",
            Self::CredentialRotate => "credential:rotate",
            Self::CredentialGrant => "credential:grant",
            Self::ApprovalRead => "approval:read",
            Self::ApprovalList => "approval:list",
            Self::ApprovalApprove => "approval:approve",
            Self::ApprovalReject => "approval:reject",
            Self::StimulusIngest => "stimulus:ingest",
            Self::NodeRead => "node:read",
            Self::NodeList => "node:list",
            Self::NodeRegister => "node:register",
            Self::NodeDeregister => "node:deregister",
            Self::NodeDrain => "node:drain",
            Self::NodeShutdown => "node:shutdown",
            Self::StackRead => "stack:read",
            Self::StackUp => "stack:up",
            Self::StackDown => "stack:down",
            Self::StackRestart => "stack:restart",
            Self::StackUpdate => "stack:update",
            Self::StackUninstall => "stack:uninstall",
            Self::KeyRead => "key:read",
            Self::KeyList => "key:list",
            Self::KeyCreate => "key:create",
            Self::KeyRevoke => "key:revoke",
            Self::TenantRead => "tenant:read",
            Self::TenantList => "tenant:list",
            Self::TenantOnboard => "tenant:onboard",
            Self::TenantProvision => "tenant:provision",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "agent:deploy" => Some(Self::AgentDeploy),
            "agent:read" => Some(Self::AgentRead),
            "agent:list" => Some(Self::AgentList),
            "agent:execute" => Some(Self::AgentExecute),
            "agent:generate" => Some(Self::AgentGenerate),
            "agent:logs" => Some(Self::AgentLogs),
            "agent:delete" => Some(Self::AgentDelete),
            "workflow:deploy" => Some(Self::WorkflowDeploy),
            "workflow:read" => Some(Self::WorkflowRead),
            "workflow:list" => Some(Self::WorkflowList),
            "workflow:run" => Some(Self::WorkflowRun),
            "workflow:validate" => Some(Self::WorkflowValidate),
            "workflow:generate" => Some(Self::WorkflowGenerate),
            "workflow:logs" => Some(Self::WorkflowLogs),
            "workflow:signal" => Some(Self::WorkflowSignal),
            "workflow:cancel" => Some(Self::WorkflowCancel),
            "workflow:delete" => Some(Self::WorkflowDelete),
            "execution:read" => Some(Self::ExecutionRead),
            "execution:list" => Some(Self::ExecutionList),
            "execution:stream" => Some(Self::ExecutionStream),
            "execution:logs" => Some(Self::ExecutionLogs),
            "execution:cancel" => Some(Self::ExecutionCancel),
            "execution:remove" => Some(Self::ExecutionRemove),
            "swarm:read" => Some(Self::SwarmRead),
            "swarm:list" => Some(Self::SwarmList),
            "swarm:cancel" => Some(Self::SwarmCancel),
            "secret:read" => Some(Self::SecretRead),
            "secret:write" => Some(Self::SecretWrite),
            "secret:list" => Some(Self::SecretList),
            "secret:delete" => Some(Self::SecretDelete),
            "secret:rotate" => Some(Self::SecretRotate),
            "credential:read" => Some(Self::CredentialRead),
            "credential:list" => Some(Self::CredentialList),
            "credential:create" => Some(Self::CredentialCreate),
            "credential:delete" => Some(Self::CredentialDelete),
            "credential:rotate" => Some(Self::CredentialRotate),
            "credential:grant" => Some(Self::CredentialGrant),
            "approval:read" => Some(Self::ApprovalRead),
            "approval:list" => Some(Self::ApprovalList),
            "approval:approve" => Some(Self::ApprovalApprove),
            "approval:reject" => Some(Self::ApprovalReject),
            "stimulus:ingest" => Some(Self::StimulusIngest),
            "node:read" => Some(Self::NodeRead),
            "node:list" => Some(Self::NodeList),
            "node:register" => Some(Self::NodeRegister),
            "node:deregister" => Some(Self::NodeDeregister),
            "node:drain" => Some(Self::NodeDrain),
            "node:shutdown" => Some(Self::NodeShutdown),
            "stack:read" => Some(Self::StackRead),
            "stack:up" => Some(Self::StackUp),
            "stack:down" => Some(Self::StackDown),
            "stack:restart" => Some(Self::StackRestart),
            "stack:update" => Some(Self::StackUpdate),
            "stack:uninstall" => Some(Self::StackUninstall),
            "key:read" => Some(Self::KeyRead),
            "key:list" => Some(Self::KeyList),
            "key:create" => Some(Self::KeyCreate),
            "key:revoke" => Some(Self::KeyRevoke),
            "tenant:read" => Some(Self::TenantRead),
            "tenant:list" => Some(Self::TenantList),
            "tenant:onboard" => Some(Self::TenantOnboard),
            "tenant:provision" => Some(Self::TenantProvision),
            _ => None,
        }
    }

    pub fn preset_readonly() -> Vec<Self> {
        vec![
            Self::AgentRead,
            Self::AgentList,
            Self::WorkflowRead,
            Self::WorkflowList,
            Self::ExecutionRead,
            Self::ExecutionList,
            Self::ExecutionLogs,
            Self::SwarmRead,
            Self::SwarmList,
            Self::NodeRead,
            Self::NodeList,
        ]
    }

    pub fn preset_execution() -> Vec<Self> {
        let mut scopes = Self::preset_readonly();
        scopes.extend([
            Self::AgentExecute,
            Self::AgentLogs,
            Self::WorkflowRun,
            Self::WorkflowLogs,
            Self::WorkflowSignal,
            Self::WorkflowCancel,
            Self::ExecutionStream,
            Self::ExecutionCancel,
            Self::SwarmCancel,
            Self::ApprovalRead,
            Self::ApprovalList,
            Self::ApprovalApprove,
            Self::ApprovalReject,
        ]);
        scopes
    }

    pub fn preset_developer() -> Vec<Self> {
        let mut scopes = Self::preset_execution();
        scopes.extend([
            Self::AgentDeploy,
            Self::AgentGenerate,
            Self::AgentDelete,
            Self::WorkflowDeploy,
            Self::WorkflowValidate,
            Self::WorkflowGenerate,
            Self::WorkflowDelete,
            Self::ExecutionRemove,
            Self::CredentialRead,
            Self::CredentialList,
            Self::CredentialCreate,
            Self::StimulusIngest,
            Self::KeyRead,
            Self::KeyList,
            Self::KeyCreate,
            Self::KeyRevoke,
        ]);
        scopes
    }

    pub fn all() -> Vec<Self> {
        vec![
            Self::AgentDeploy,
            Self::AgentRead,
            Self::AgentList,
            Self::AgentExecute,
            Self::AgentGenerate,
            Self::AgentLogs,
            Self::AgentDelete,
            Self::WorkflowDeploy,
            Self::WorkflowRead,
            Self::WorkflowList,
            Self::WorkflowRun,
            Self::WorkflowValidate,
            Self::WorkflowGenerate,
            Self::WorkflowLogs,
            Self::WorkflowSignal,
            Self::WorkflowCancel,
            Self::WorkflowDelete,
            Self::ExecutionRead,
            Self::ExecutionList,
            Self::ExecutionStream,
            Self::ExecutionLogs,
            Self::ExecutionCancel,
            Self::ExecutionRemove,
            Self::SwarmRead,
            Self::SwarmList,
            Self::SwarmCancel,
            Self::SecretRead,
            Self::SecretWrite,
            Self::SecretList,
            Self::SecretDelete,
            Self::SecretRotate,
            Self::CredentialRead,
            Self::CredentialList,
            Self::CredentialCreate,
            Self::CredentialDelete,
            Self::CredentialRotate,
            Self::CredentialGrant,
            Self::ApprovalRead,
            Self::ApprovalList,
            Self::ApprovalApprove,
            Self::ApprovalReject,
            Self::StimulusIngest,
            Self::NodeRead,
            Self::NodeList,
            Self::NodeRegister,
            Self::NodeDeregister,
            Self::NodeDrain,
            Self::NodeShutdown,
            Self::StackRead,
            Self::StackUp,
            Self::StackDown,
            Self::StackRestart,
            Self::StackUpdate,
            Self::StackUninstall,
            Self::KeyRead,
            Self::KeyList,
            Self::KeyCreate,
            Self::KeyRevoke,
            Self::TenantRead,
            Self::TenantList,
            Self::TenantOnboard,
            Self::TenantProvision,
        ]
    }
}

impl fmt::Display for ApiScope {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
