// Copyright (c) 2026 100monkeys.ai
// SPDX-License-Identifier: AGPL-3.0
//! # SMCP Attestation (ADR-035 §4.1)
//!
//! Defines the attestation handshake types and service trait. Attestation is the
//! one-time ceremony at the start of each agent execution during which the agent:
//! 1. Generates an ephemeral Ed25519 keypair (in-container, never stored)
//! 2. Sends the public key + container ID to the orchestrator
//! 3. Receives a signed `SecurityToken` (JWT) that proves its identity and
//!    authorised `SecurityContext` for all subsequent tool calls
//!
//! ## Security Properties
//!
//! - The orchestrator verifies the `container_id` matches the execution's known container
//! - The `public_key_pem` is stored in the `SmcpSession` for signature verification
//! - The JWT lifetime matches the session TTL (1 hour)
//! - The private key never leaves the container and is never written to disk

use anyhow::Result;
use async_trait::async_trait;

/// The agent's initial attestation message sent to the orchestrator.
///
/// Contains the ephemeral Ed25519 public key generated for this execution.
/// The orchestrator validates `container_id` against the known running containers
/// for the execution before issuing a `SecurityToken`.
#[derive(Debug, Clone)]
pub struct AttestationRequest {
    /// AEGIS `AgentId` (UUID string) of the agent being executed.
    pub agent_id: String,
    /// AEGIS `ExecutionId` (UUID string) of the current execution.
    pub execution_id: String,
    /// Docker container ID of the running agent container.
    /// Used to bind the session to a specific container instance.
    pub container_id: String,
    /// Der-encoded or PEM-encoded Ed25519 public key generated by the agent for this execution.
    /// Stored in the `SmcpSession`; never persisted beyond session lifetime.
    pub public_key_pem: String,
}

/// The orchestrator's response to a successful attestation handshake.
#[derive(Debug, Clone)]
pub struct AttestationResponse {
    /// Signed JWT (`SecurityToken`) encoding `ContextClaims`.
    /// The agent must include this token in every subsequent `SmcpEnvelope`.
    pub security_token: String,
}

/// Service responsible for completing the SMCP attestation handshake.
///
/// The production implementation validates the container identity and issues a
/// signed JWT. Called once per execution at startup, before any tool calls.
///
/// # Security
///
/// Implementations must verify that `request.container_id` corresponds to a
/// container actually running under the claimed `execution_id`. Failure to do
/// this validation would allow a compromised container to impersonate another
/// agent execution.
///
/// See ADR-035 §4.1 (Attestation Flow).
#[async_trait]
pub trait AttestationService: Send + Sync {
    /// Validate the attestation request and issue a `SecurityToken`.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - `container_id` is not a currently-running container for `execution_id`
    /// - `public_key_pem` is not a valid Ed25519 public key
    /// - JWT signing fails
    async fn attest(&self, request: AttestationRequest) -> Result<AttestationResponse>;
}
