apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "architect-agent"
  version: "1.0.0"
  description: "Software architect for The Forge - designs technical solutions and system architecture"
  labels:
    role: "worker"
    category: "forge"
    function: "design"

spec:
  runtime:
    language: "python"
    version: "3.10"
    entrypoint: "main.py"
  
  task:
    instruction: |
      You are an expert Software Architect. Design technical solutions based on requirements.
      Focus on clean, maintainable design. Output: Architecture Overview, Component Design, Data Models, API Contracts, Technology Choices, Implementation Plan.
  
  execution:
    mode: "iterative"  # Enable refinement for architecture quality
    max_iterations: 5
    memory: true  # Learn from architectural patterns
    
    validation:
      semantic:
        enabled: true
        threshold: 0.85  # High bar for architecture quality
        prompt: |
          Evaluate the architecture design against these criteria:
          {criteria}
          
          Verify:
          - All required sections are present and complete
          - Design choices are well-justified
          - Component boundaries are clear
          - API contracts are well-defined
          - Technical choices are appropriate for requirements
  
  security:
    network:
      mode: "allow"
      allowlist:
        - "api.openai.com"
    
    resources:
      cpu: 1000       # 1.0 CPU core (architecture work is compute-intensive)
      memory: "1Gi"
      timeout: "180s"
