apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "coder-agent"
  version: "1.0.0"
  description: "Implementation engineer for The Forge - writes production-quality code"
  labels:
    role: "worker"
    category: "forge"
    function: "implementation"

spec:
  runtime:
    language: "python"
    version: "3.10"

  
  task:
    instruction: |
      You are an expert Software Engineer. Write clean, production-quality code with proper error handling, documentation, and unit tests.
      Follow language conventions, use meaningful names, keep functions focused. Code should be merge-ready.
    prompt_template: |
      {agent_instruction}
      
      User: {user_input}
      Engineer:
  
  execution:
    mode: "iterative"  # Enable refinement for code quality
    max_iterations: 5
    memory: true  # Learn from coding patterns and corrections
    
    validation:
      semantic:
        enabled: true
        threshold: 0.80
        prompt: |
          Assess the code quality against professional standards:
          {criteria}
          
          Check:
          - Code compiles/runs without errors
          - Proper error handling exists
          - Documentation is clear and complete
          - Unit tests cover key functionality
          - Follows language conventions and best practices
  
  security:
    network:
      mode: "allow"
      allowlist:
        - "api.openai.com"
    
    resources:
      cpu: 1000       # 1.0 CPU core (code generation is intensive)
      memory: "1Gi"
      timeout: "300s"
