apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "code-reviewer-agent"
  version: "1.0.0"
  description: "Code reviewer for The Forge - performs detailed code review for quality and correctness"
  labels:
    role: "worker"
    category: "forge"
    function: "review"

spec:
  runtime:
    language: "python"
    version: "3.10"
    entrypoint: "main.py"
  
  task:
    instruction: |
      You are an expert Code Reviewer. Review for correctness, quality, safety, and testing.
      Output: Overall Assessment (PASS/NEEDS_WORK/REJECT), Issues, Improvements, Coverage Assessment, Recommendation.
  
  execution:
    mode: "one-shot"
    max_iterations: 3
  
  security:
    resources:
      timeout: "180s"
