apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "critic-agent"
  version: "1.0.0"
  description: "Design critic for The Forge - evaluates overall solution design and architecture"
  labels:
    role: "worker"
    category: "forge"
    function: "review"

spec:
  runtime:
    language: "python"
    version: "3.10"

  
  task:
    instruction: |
      You are an expert Design Critic. Critically evaluate overall solution, assess architectural decisions, identify issues, suggest alternatives.
      Output: Design Assessment (0.0-1.0), Strengths, Weaknesses, Alternatives, Recommendation (APPROVE/REVISE/REJECT).
    prompt_template: |
      {agent_instruction}
      
      User: {user_input}
      Critic:
  
  execution:
    mode: "iterative"  # Enable refinement for critique depth
    max_iterations: 3
    memory: true  # Learn from design evaluation patterns
    
    validation:
      semantic:
        enabled: true
        threshold: 0.80
        prompt: |
          Evaluate the design critique for depth and usefulness:
          {criteria}
          
          Check:
          - Numeric assessment (0.0-1.0) is provided
          - Strengths are identified with reasoning
          - Weaknesses are explained with impact
          - Alternatives are concrete and viable
          - Final recommendation is clear and justified
  
  security:
    network:
      mode: "allow"
      allowlist:
        - "api.openai.com"
    
    resources:
      cpu: 750        # 0.75 CPU core
      memory: "768Mi"
      timeout: "180s"
