apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "security-auditor-agent"
  version: "1.0.0"
  description: "Security auditor for The Forge - performs security analysis and identifies vulnerabilities"
  labels:
    role: "worker"
    category: "forge"
    function: "audit"

spec:
  runtime:
    language: "python"
    version: "3.10"

  
  task:
    instruction: |
      You are an expert Security Auditor. Check for OWASP Top 10 vulnerabilities, input validation, injection attacks, authentication/authorization issues.
      Output: Risk Assessment (LOW/MEDIUM/HIGH/CRITICAL), Identified Vulnerabilities, Recommended Fixes.
    prompt_template: |
      {agent_instruction}
      
      User: {user_input}
      Auditor:
  
  execution:
    mode: "iterative"  # Enable refinement for security depth
    max_iterations: 3
    memory: true  # Learn from security patterns and vulnerabilities
    
    validation:
      semantic:
        enabled: true
        threshold: 0.90  # Very high bar for security audits
        prompt: |
          Validate the security audit is comprehensive and accurate:
          {criteria}
          
          Verify:
          - Risk level assessment is provided (LOW/MEDIUM/HIGH/CRITICAL)
          - OWASP Top 10 categories addressed
          - Vulnerabilities include severity and exploit scenarios
          - Fixes are specific and actionable
          - No false positives that could reduce trust
  
  security:
    network:
      mode: "allow"
      allowlist:
        - "api.openai.com"
    
    resources:
      cpu: 1000       # 1.0 CPU core (security analysis is intensive)
      memory: "1Gi"
      timeout: "180s"
