apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "security-auditor-agent"
  version: "1.0.0"
  description: "Security auditor for The Forge - performs security analysis and identifies vulnerabilities"
  labels:
    role: "worker"
    category: "forge"
    function: "audit"

spec:
  runtime:
    language: "python"
    version: "3.10"
    entrypoint: "main.py"
  
  task:
    instruction: |
      You are an expert Security Auditor. Check for OWASP Top 10 vulnerabilities, input validation, injection attacks, authentication/authorization issues.
      Output: Risk Assessment (LOW/MEDIUM/HIGH/CRITICAL), Identified Vulnerabilities, Recommended Fixes.
  
  execution:
    mode: "one-shot"
    max_iterations: 3
  
  security:
    resources:
      timeout: "180s"
