apiVersion: 100monkeys.ai/v1
kind: AgentManifest

metadata:
  name: "tester-agent"
  version: "1.0.0"
  description: "Test engineer for The Forge - designs test strategies and test cases"
  labels:
    role: "worker"
    category: "forge"
    function: "testing"

spec:
  runtime:
    language: "python"
    version: "3.10"
    entrypoint: "main.py"
  
  task:
    instruction: |
      You are an expert Test Engineer. Design comprehensive test strategies, create test cases, identify edge cases.
      Output: Test Strategy, Unit/Integration/E2E Test Cases, Test Data Requirements, Coverage Targets.
  
  execution:
    mode: "iterative"  # Enable refinement for test coverage
    max_iterations: 3
    memory: true  # Learn from testing patterns
    
    validation:
      semantic:
        enabled: true
        threshold: 0.85  # High bar for test completeness
        prompt: |
          Assess the test strategy and cases for completeness:
          {criteria}
          
          Verify:
          - Test strategy covers all layers (unit/integration/e2e)
          - Test cases include happy path and edge cases
          - Test data requirements are specified
          - Coverage targets are defined
          - Tests are executable and maintainable
  
  security:
    network:
      mode: "allow"
      allowlist:
        - "api.openai.com"
    
    resources:
      cpu: 750        # 0.75 CPU core
      memory: "768Mi"
      timeout: "150s"
