// Copyright (c) 2026 100monkeys.ai
// SPDX-License-Identifier: AGPL-3.0
//! # SEAL Attestation (ADR-035 §4.1)
//!
//! Defines the attestation handshake types and service trait. Attestation is the
//! one-time ceremony at the start of each agent execution during which the agent:
//! 1. Generates an ephemeral Ed25519 keypair (in-container, never stored)
//! 2. Sends the public key + container ID to the orchestrator
//! 3. Receives a signed `SecurityToken` (JWT) that proves its identity and
//!    authorised `SecurityContext` for all subsequent tool calls
//!
//! ## Security Properties
//!
//! - The orchestrator verifies the `container_id` matches the execution's known container
//! - The `public_key_pem` is stored in the `SealSession` for signature verification
//! - The JWT lifetime matches the session TTL (1 hour)
//! - The private key never leaves the container and is never written to disk

use anyhow::Result;
use async_trait::async_trait;

use crate::domain::tenant::TenantId;

/// The agent's initial attestation message sent to the orchestrator.
///
/// Contains the ephemeral Ed25519 public key generated for this execution.
/// The orchestrator validates `container_id` against the known running containers
/// for the execution before issuing a `SecurityToken`.
#[derive(Debug, Clone)]
pub struct AttestationRequest {
    /// Optional AEGIS `AgentId` (UUID string) of the agent being executed.
    ///
    /// Zaru-facing attestation may omit this and let the orchestrator mint a
    /// session-scoped identifier instead.
    pub agent_id: Option<String>,
    /// Optional AEGIS `ExecutionId` (UUID string) of the current execution.
    ///
    /// Zaru-facing attestation may omit this and let the orchestrator mint a
    /// session-scoped execution identifier instead.
    pub execution_id: Option<String>,
    /// Optional container/workload identifier of the running caller.
    /// Used to bind the session to a specific workload instance when available.
    pub container_id: Option<String>,
    /// Der-encoded or PEM-encoded Ed25519 public key generated by the agent for this execution.
    /// Stored in the `SealSession`; never persisted beyond session lifetime.
    pub public_key_pem: String,
    /// Optional explicit SecurityContext name to bind this attestation to.
    ///
    /// This is the authoritative Zaru path: the authenticated user tier is
    /// mapped to `zaru-free`, `zaru-pro`, or `zaru-enterprise` before the
    /// attestation request reaches the orchestrator.
    pub security_context: Option<String>,
    /// Optional upstream principal/workload subject for audit correlation.
    pub principal_subject: Option<String>,
    /// Optional upstream end-user identifier for consumer-facing Zaru sessions.
    pub user_id: Option<String>,
    /// Optional upstream workload identifier for audit correlation.
    pub workload_id: Option<String>,
    /// Optional upstream Zaru tier string used to derive the security context.
    pub zaru_tier: Option<String>,
    /// Tenant identity of the requesting principal (ADR-056).
    ///
    /// Used to enforce SecurityContext name ownership: `zaru-*` contexts require
    /// a consumer tenant, `tenant-{slug}-*` contexts require the matching
    /// enterprise tenant, and `aegis-system-*` contexts require the system tenant.
    pub tenant_id: TenantId,
}

/// The orchestrator's response to a successful attestation handshake.
#[derive(Debug, Clone)]
pub struct AttestationResponse {
    /// Overall result status (e.g. `"success"`).
    pub status: String,
    /// Signed JWT (`SecurityToken`) encoding `ContextClaims`.
    /// The agent must include this token in every subsequent `SealEnvelope`.
    pub security_token: String,
    /// ISO-8601 UTC timestamp at which the token expires.
    pub expires_at: String,
    /// Optional session identifier for audit correlation.
    pub session_id: Option<String>,
}

/// Service responsible for completing the SEAL attestation handshake.
///
/// The production implementation validates the container identity and issues a
/// signed JWT. Called once per execution at startup, before any tool calls.
///
/// # Security
///
/// Implementations must verify that `request.container_id` corresponds to a
/// container actually running under the claimed `execution_id`. Failure to do
/// this validation would allow a compromised container to impersonate another
/// agent execution.
///
/// See ADR-035 §4.1 (Attestation Flow).
#[async_trait]
pub trait AttestationService: Send + Sync {
    /// Validate the attestation request and issue a `SecurityToken`.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - `container_id` is not a currently-running container for `execution_id`
    /// - `public_key_pem` is not a valid Ed25519 public key
    /// - JWT signing fails
    async fn attest(&self, request: AttestationRequest) -> Result<AttestationResponse>;
}
