// Copyright (c) 2026 100monkeys.ai
// SPDX-License-Identifier: AGPL-3.0
//! # AEGIS Runtime Protocol Buffer Definitions
//!
//! Shared home for the generated code from `proto/aegis_runtime.proto`.
//! Both the gRPC server (`presentation::grpc::server`) and the gRPC client that
//! forwards Cortex RPCs (`infrastructure::cortex_client`) reference types from
//! this single module to ensure they share identical Rust types.
//!
//! # Code Generation
//!
//! All code included here is generated by `tonic-build` in `build.rs` and
//! placed in `OUT_DIR`. Do not manually edit the generated code.
//!
//! # Architecture
//!
//! - **Layer:** Infrastructure Layer
//! - **Purpose:** Central proto type registry for `aegis.runtime.v1`
//! - **Related ADRs:** ADR-026 (gRPC API Architecture), ADR-042 (Separate Cortex Repository)

tonic::include_proto!("aegis.runtime.v1");
