// Copyright (c) 2026 100monkeys.ai
// SPDX-License-Identifier: AGPL-3.0
//! # Secrets Manager (BC-11, ADR-034)
//!
//! Implements the OpenBao secrets management integration described in ADR-034.
//!
//! ## Implementation details
//!
//! 1. **OpenBao Deployment** — HA cluster with Raft backend.
//! 2. **AppRole Auth** — orchestrator nodes authenticate with Role ID + Secret ID.
//! 3. **KV Engine** — static API keys stored at `<tenant>/kv/<name>`.
//! 4. **Dynamic Secrets** — database credentials auto-rotated per `DynamicSecret.ttl`.
//! 5. **Transit Engine** — `sign()`, `verify()`, `encrypt()`, and `decrypt()`
//!    without key distribution.
//! 6. **Keymaster Pattern** — only the orchestrator accesses OpenBao;
//!    agents receive credentials via `spec.environment` injection, never via
//!    direct vault calls.
//!
//! See ADR-034 (OpenBao Secrets Management), AGENTS.md §BC-11.

use crate::domain::mcp::{CredentialRef, CredentialStoreType};
use crate::domain::node_config::OpenBaoConfig;
use anyhow::Result;
use async_trait::async_trait;
use base64::Engine;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;
use thiserror::Error;
use tokio::sync::RwLock;
use tracing::{debug, info, warn};
use vaultrs::client::{Client, VaultClient, VaultClientSettingsBuilder};

/// Error types for secrets management operations.
#[derive(Debug, Error)]
pub enum SecretsError {
    /// Secret not found at the specified path.
    #[error("Secret not found: {path}")]
    SecretNotFound { path: String },

    /// Failed to communicate with OpenBao.
    #[error("OpenBao connection error: {0}")]
    ConnectionError(String),

    /// Invalid secret path or format.
    #[error("Invalid secret path: {0}")]
    InvalidPath(String),

    /// Missing or invalid configuration.
    #[error("Invalid configuration: {0}")]
    ConfigError(String),

    /// Dynamic secret generation failed.
    #[error("Dynamic secret error: {0}")]
    DynamicSecretError(String),

    /// Transit engine operation failed.
    #[error("Transit engine error: {0}")]
    TransitError(String),

    /// Credential resolution failed.
    #[error("Credential resolution error: {0}")]
    CredentialResolutionError(String),
}

impl From<vaultrs::error::ClientError> for SecretsError {
    fn from(err: vaultrs::error::ClientError) -> Self {
        match err {
            vaultrs::error::ClientError::APIError { code: 404, .. } => {
                SecretsError::SecretNotFound {
                    path: "unknown".into(),
                }
            }
            _ => SecretsError::ConnectionError(err.to_string()),
        }
    }
}

/// Dynamic credential generated by OpenBao with limited TTL.
#[derive(Debug, Clone)]
pub struct DynamicSecret {
    pub lease_id: String,
    pub lease_duration: Duration,
    pub renewable: bool,
    pub data: HashMap<String, String>,
}

/// Abstract interface for secret storage (OpenBao implementation, Mock for testing).
///
/// This trait follows ADR-034 §SecretStore — every method maps to an OpenBao
/// engine capability: KV read/write, dynamic credential generation, lease
/// lifecycle, and Transit Engine cryptographic operations.
#[async_trait]
pub trait SecretStore: Send + Sync {
    /// Read static secret from KV store.
    async fn read(&self, engine: &str, path: &str)
        -> Result<HashMap<String, String>, SecretsError>;

    /// Write static secret to KV store.
    async fn write(
        &self,
        engine: &str,
        path: &str,
        secret: HashMap<String, String>,
    ) -> Result<(), SecretsError>;

    /// Generate dynamic credentials (e.g. database engine).
    async fn generate_dynamic(
        &self,
        engine: &str,
        role: &str,
    ) -> Result<DynamicSecret, SecretsError>;

    /// Renew dynamic secret lease.
    async fn renew_lease(
        &self,
        lease_id: &str,
        increment: Duration,
    ) -> Result<Duration, SecretsError>;

    /// Revoke dynamic secret lease.
    async fn revoke_lease(&self, lease_id: &str) -> Result<(), SecretsError>;

    /// Sign data with Transit Engine.
    async fn transit_sign(&self, key_name: &str, data: &[u8]) -> Result<String, SecretsError>;

    /// Verify signature with Transit Engine.
    async fn transit_verify(
        &self,
        key_name: &str,
        data: &[u8],
        signature: &str,
    ) -> Result<bool, SecretsError>;

    /// Encrypt data with Transit Engine.
    async fn transit_encrypt(
        &self,
        key_name: &str,
        plaintext: &[u8],
    ) -> Result<String, SecretsError>;

    /// Decrypt data with Transit Engine.
    async fn transit_decrypt(
        &self,
        key_name: &str,
        ciphertext: &str,
    ) -> Result<Vec<u8>, SecretsError>;
}

// ---------------------------------------------------------------------------
// OpenBaoSecretStore — production implementation using AppRole auth
// ---------------------------------------------------------------------------

/// OpenBao implementation using AppRole authentication and token auto-renewal.
pub struct OpenBaoSecretStore {
    client: Arc<RwLock<VaultClient>>,
}

impl OpenBaoSecretStore {
    /// Creates a new `OpenBaoSecretStore`, authenticates via AppRole, and spawns the renewal loop.
    pub async fn new(config: OpenBaoConfig) -> Result<Self, SecretsError> {
        // 1. Create client (unauthenticated)
        let mut builder = VaultClientSettingsBuilder::default();
        builder.address(&config.address);

        if let Some(namespace) = &config.namespace {
            builder.set_namespace(namespace.clone());
        }

        if let Some(ca_cert) = &config.tls.ca_cert {
            builder.ca_certs(vec![ca_cert.clone()]);
        }

        let settings = builder
            .build()
            .map_err(|e| SecretsError::ConfigError(e.to_string()))?;
        let mut client =
            VaultClient::new(settings).map_err(|e| SecretsError::ConfigError(e.to_string()))?;

        // 2. Authenticate via AppRole
        let secret_id = std::env::var(&config.approle.secret_id_env_var).unwrap_or_default();

        if config.auth_method != "approle" {
            return Err(SecretsError::ConfigError(format!(
                "Unsupported auth method: {}",
                config.auth_method
            )));
        }

        debug!("Authenticating with OpenBao AppRole...");

        let auth_response =
            vaultrs::auth::approle::login(&client, "approle", &config.approle.role_id, &secret_id)
                .await?;

        // 3. Set token in client
        client.set_token(&auth_response.client_token);
        info!("Successfully authenticated with OpenBao AppRole");

        let shared_client = Arc::new(RwLock::new(client));

        // 4. Start token renewal background task
        let renewal_client = shared_client.clone();
        tokio::spawn(Self::token_renewal_loop(renewal_client));

        Ok(Self {
            client: shared_client,
        })
    }

    async fn token_renewal_loop(client: Arc<RwLock<VaultClient>>) {
        // Renew every 30 minutes (token TTL is 1 hour per ADR-034 §Authentication)
        let mut interval = tokio::time::interval(Duration::from_secs(1800));
        loop {
            interval.tick().await;

            let client_guard = client.read().await;
            match vaultrs::token::renew_self(&*client_guard, None).await {
                Ok(_) => debug!("Successfully renewed OpenBao token"),
                Err(e) => warn!("Failed to renew OpenBao token: {}", e),
            }
        }
    }
}

#[async_trait]
impl SecretStore for OpenBaoSecretStore {
    async fn read(
        &self,
        engine: &str,
        path: &str,
    ) -> Result<HashMap<String, String>, SecretsError> {
        let client = self.client.read().await;
        let secret: HashMap<String, String> = vaultrs::kv2::read(&*client, engine, path).await?;
        Ok(secret)
    }

    async fn write(
        &self,
        engine: &str,
        path: &str,
        secret: HashMap<String, String>,
    ) -> Result<(), SecretsError> {
        let client = self.client.read().await;
        vaultrs::kv2::set(&*client, engine, path, &secret).await?;
        Ok(())
    }

    async fn generate_dynamic(
        &self,
        engine_path: &str,
        role: &str,
    ) -> Result<DynamicSecret, SecretsError> {
        let client = self.client.read().await;
        // Dynamic secrets are read from `{engine}/creds/{role}`.
        // The vaultrs crate models individual database engines, but we use
        // the generic logical read to support *any* dynamic engine uniformly.
        let creds_path = format!("{}/creds/{}", engine_path, role);
        let response: HashMap<String, String> =
            vaultrs::kv2::read(&*client, engine_path, &format!("creds/{}", role))
                .await
                .map_err(|e| {
                    SecretsError::DynamicSecretError(format!(
                        "Failed to generate dynamic secret at {}: {}",
                        creds_path, e
                    ))
                })?;

        Ok(DynamicSecret {
            lease_id: response.get("lease_id").cloned().unwrap_or_default(),
            lease_duration: Duration::from_secs(
                response
                    .get("lease_duration")
                    .and_then(|v| v.parse::<u64>().ok())
                    .unwrap_or(300),
            ),
            renewable: response
                .get("renewable")
                .map(|v| v == "true")
                .unwrap_or(false),
            data: response,
        })
    }

    async fn renew_lease(
        &self,
        lease_id: &str,
        increment: Duration,
    ) -> Result<Duration, SecretsError> {
        // vaultrs 0.7 does not expose sys/leases endpoints directly.
        // Use the raw HTTP client to call PUT /v1/sys/leases/renew.
        let client = self.client.read().await;
        let address = client.settings().address.clone();
        let token = client.settings().token.clone();
        let url = format!("{}v1/sys/leases/renew", address);
        let body = serde_json::json!({
            "lease_id": lease_id,
            "increment": format!("{}s", increment.as_secs()),
        });
        let http_resp = reqwest::Client::new()
            .put(&url)
            .header("X-Vault-Token", &token)
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                SecretsError::DynamicSecretError(format!("Lease renewal HTTP failed: {}", e))
            })?;
        if !http_resp.status().is_success() {
            return Err(SecretsError::DynamicSecretError(format!(
                "Lease renewal failed with status: {}",
                http_resp.status()
            )));
        }
        // The response contains lease_duration in the top-level JSON
        let resp_json: serde_json::Value = http_resp.json().await.map_err(|e| {
            SecretsError::DynamicSecretError(format!("Lease renewal response parse failed: {}", e))
        })?;
        let duration_secs = resp_json["lease_duration"]
            .as_u64()
            .unwrap_or(increment.as_secs());
        Ok(Duration::from_secs(duration_secs))
    }

    async fn revoke_lease(&self, lease_id: &str) -> Result<(), SecretsError> {
        // vaultrs 0.7 does not expose sys/leases endpoints directly.
        // Use the raw HTTP client to call PUT /v1/sys/leases/revoke.
        let client = self.client.read().await;
        let address = client.settings().address.clone();
        let token = client.settings().token.clone();
        let url = format!("{}v1/sys/leases/revoke", address);
        let body = serde_json::json!({ "lease_id": lease_id });
        let http_resp = reqwest::Client::new()
            .put(&url)
            .header("X-Vault-Token", &token)
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                SecretsError::DynamicSecretError(format!("Lease revocation HTTP failed: {}", e))
            })?;
        if !http_resp.status().is_success() {
            return Err(SecretsError::DynamicSecretError(format!(
                "Lease revocation failed with status: {}",
                http_resp.status()
            )));
        }
        Ok(())
    }

    async fn transit_sign(&self, key_name: &str, data: &[u8]) -> Result<String, SecretsError> {
        let client = self.client.read().await;
        let encoded_data = base64::engine::general_purpose::STANDARD.encode(data);
        let resp = vaultrs::transit::data::sign(&*client, "transit", key_name, &encoded_data, None)
            .await
            .map_err(|e| SecretsError::TransitError(format!("Sign failed: {}", e)))?;
        Ok(resp.signature)
    }

    async fn transit_verify(
        &self,
        key_name: &str,
        data: &[u8],
        signature: &str,
    ) -> Result<bool, SecretsError> {
        use vaultrs::api::transit::requests::VerifySignedDataRequestBuilder;
        let client = self.client.read().await;
        let encoded_data = base64::engine::general_purpose::STANDARD.encode(data);
        let mut opts = VerifySignedDataRequestBuilder::default();
        opts.signature(signature);
        let resp = vaultrs::transit::data::verify(
            &*client,
            "transit",
            key_name,
            &encoded_data,
            Some(&mut opts),
        )
        .await
        .map_err(|e| SecretsError::TransitError(format!("Verify failed: {}", e)))?;
        Ok(resp.valid)
    }

    async fn transit_encrypt(
        &self,
        key_name: &str,
        plaintext: &[u8],
    ) -> Result<String, SecretsError> {
        let client = self.client.read().await;
        let encoded_data = base64::engine::general_purpose::STANDARD.encode(plaintext);
        let resp =
            vaultrs::transit::data::encrypt(&*client, "transit", key_name, &encoded_data, None)
                .await
                .map_err(|e| SecretsError::TransitError(format!("Encrypt failed: {}", e)))?;
        Ok(resp.ciphertext)
    }

    async fn transit_decrypt(
        &self,
        key_name: &str,
        ciphertext: &str,
    ) -> Result<Vec<u8>, SecretsError> {
        let client = self.client.read().await;
        let resp = vaultrs::transit::data::decrypt(&*client, "transit", key_name, ciphertext, None)
            .await
            .map_err(|e| SecretsError::TransitError(format!("Decrypt failed: {}", e)))?;
        base64::engine::general_purpose::STANDARD
            .decode(&resp.plaintext)
            .map_err(|e| SecretsError::TransitError(format!("Base64 decode failed: {}", e)))
    }
}

// ---------------------------------------------------------------------------
// MockSecretStore — in-memory implementation for unit tests
// ---------------------------------------------------------------------------

/// In-memory mock for `SecretStore` used in unit tests (ADR-034 §Consequences).
///
/// Stores KV data in a `HashMap`, returns deterministic results for transit
/// operations, and generates synthetic dynamic secrets.
pub struct MockSecretStore {
    kv_store: RwLock<HashMap<String, HashMap<String, String>>>,
}

impl MockSecretStore {
    pub fn new() -> Self {
        Self {
            kv_store: RwLock::new(HashMap::new()),
        }
    }

    fn kv_key(engine: &str, path: &str) -> String {
        format!("{}/{}", engine, path)
    }
}

impl Default for MockSecretStore {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl SecretStore for MockSecretStore {
    async fn read(
        &self,
        engine: &str,
        path: &str,
    ) -> Result<HashMap<String, String>, SecretsError> {
        let store = self.kv_store.read().await;
        store
            .get(&Self::kv_key(engine, path))
            .cloned()
            .ok_or_else(|| SecretsError::SecretNotFound {
                path: format!("{}/{}", engine, path),
            })
    }

    async fn write(
        &self,
        engine: &str,
        path: &str,
        secret: HashMap<String, String>,
    ) -> Result<(), SecretsError> {
        let mut store = self.kv_store.write().await;
        store.insert(Self::kv_key(engine, path), secret);
        Ok(())
    }

    async fn generate_dynamic(
        &self,
        engine: &str,
        role: &str,
    ) -> Result<DynamicSecret, SecretsError> {
        Ok(DynamicSecret {
            lease_id: format!("{}/creds/{}/lease-mock-001", engine, role),
            lease_duration: Duration::from_secs(300),
            renewable: true,
            data: HashMap::from([
                ("username".to_string(), format!("v-mock-{}-abc123", role)),
                ("password".to_string(), "mock-dynamic-password".to_string()),
            ]),
        })
    }

    async fn renew_lease(
        &self,
        _lease_id: &str,
        increment: Duration,
    ) -> Result<Duration, SecretsError> {
        Ok(increment)
    }

    async fn revoke_lease(&self, _lease_id: &str) -> Result<(), SecretsError> {
        Ok(())
    }

    async fn transit_sign(&self, key_name: &str, data: &[u8]) -> Result<String, SecretsError> {
        // Deterministic mock signature: "vault:v1:<key_name>:<base64(data)>"
        let encoded = base64::engine::general_purpose::STANDARD.encode(data);
        Ok(format!("vault:v1:{}:{}", key_name, encoded))
    }

    async fn transit_verify(
        &self,
        key_name: &str,
        data: &[u8],
        signature: &str,
    ) -> Result<bool, SecretsError> {
        let expected = self.transit_sign(key_name, data).await?;
        Ok(signature == expected)
    }

    async fn transit_encrypt(
        &self,
        key_name: &str,
        plaintext: &[u8],
    ) -> Result<String, SecretsError> {
        // Deterministic mock ciphertext: "vault:v1:<key_name>:<base64(plaintext)>"
        let encoded = base64::engine::general_purpose::STANDARD.encode(plaintext);
        Ok(format!("vault:v1:{}:{}", key_name, encoded))
    }

    async fn transit_decrypt(
        &self,
        key_name: &str,
        ciphertext: &str,
    ) -> Result<Vec<u8>, SecretsError> {
        let prefix = format!("vault:v1:{}:", key_name);
        let encoded = ciphertext.strip_prefix(&prefix).ok_or_else(|| {
            SecretsError::TransitError(format!(
                "Invalid mock ciphertext format (expected prefix '{}')",
                prefix
            ))
        })?;
        base64::engine::general_purpose::STANDARD
            .decode(encoded)
            .map_err(|e| SecretsError::TransitError(format!("Base64 decode failed: {}", e)))
    }
}

// ---------------------------------------------------------------------------
// SecretsManager — Application-layer facade (Keymaster pattern)
// ---------------------------------------------------------------------------

/// The main entry point for the Application layer to interact with secrets,
/// following the Keymaster architectural pattern (ADR-034).
///
/// Only the orchestrator accesses the secret store; agents never communicate
/// with OpenBao directly. This struct wraps a `SecretStore` implementation
/// and provides convenience methods including credential resolution.
pub struct SecretsManager {
    store: Arc<dyn SecretStore>,
}

impl SecretsManager {
    /// Creates a new `SecretsManager` with the underlying OpenBao store.
    pub async fn from_config(config: &OpenBaoConfig) -> Result<Self, SecretsError> {
        let store = OpenBaoSecretStore::new(config.clone()).await?;
        Ok(Self {
            store: Arc::new(store),
        })
    }

    /// Creates a new `SecretsManager` wrapping an arbitrary `SecretStore`
    /// (used for testing with `MockSecretStore`).
    pub fn from_store(store: Arc<dyn SecretStore>) -> Self {
        Self { store }
    }

    /// Read a secret from OpenBao KV engine.
    pub async fn read_secret(
        &self,
        engine: &str,
        path: &str,
    ) -> Result<HashMap<String, String>, SecretsError> {
        self.store.read(engine, path).await
    }

    /// Read a single value from a KV engine path.
    pub async fn read_secret_field(
        &self,
        engine: &str,
        path: &str,
        field: &str,
    ) -> Result<String, SecretsError> {
        let mut secret = self.store.read(engine, path).await?;
        secret
            .remove(field)
            .ok_or_else(|| SecretsError::SecretNotFound {
                path: format!("{}/{}#{}", engine, path, field),
            })
    }

    /// Generate a dynamic secret (e.g., database credentials with TTL).
    pub async fn generate_dynamic_secret(
        &self,
        engine: &str,
        role: &str,
    ) -> Result<DynamicSecret, SecretsError> {
        self.store.generate_dynamic(engine, role).await
    }

    /// Renew a dynamic secret lease.
    pub async fn renew_lease(
        &self,
        lease_id: &str,
        increment: Duration,
    ) -> Result<Duration, SecretsError> {
        self.store.renew_lease(lease_id, increment).await
    }

    /// Revoke a dynamic secret lease early.
    pub async fn revoke_lease(&self, lease_id: &str) -> Result<(), SecretsError> {
        self.store.revoke_lease(lease_id).await
    }

    /// Sign data using OpenBao Transit Engine.
    pub async fn sign(&self, key_name: &str, data: &[u8]) -> Result<String, SecretsError> {
        self.store.transit_sign(key_name, data).await
    }

    /// Verify a signature using OpenBao Transit Engine.
    pub async fn verify(
        &self,
        key_name: &str,
        data: &[u8],
        signature: &str,
    ) -> Result<bool, SecretsError> {
        self.store.transit_verify(key_name, data, signature).await
    }

    /// Encrypt data using OpenBao Transit Engine.
    pub async fn encrypt(&self, key_name: &str, plaintext: &[u8]) -> Result<String, SecretsError> {
        self.store.transit_encrypt(key_name, plaintext).await
    }

    /// Decrypt data using OpenBao Transit Engine.
    pub async fn decrypt(&self, key_name: &str, ciphertext: &str) -> Result<Vec<u8>, SecretsError> {
        self.store.transit_decrypt(key_name, ciphertext).await
    }

    /// Resolve a [`CredentialRef`] to its plaintext value.
    ///
    /// Dispatches to the appropriate backend:
    /// - `CredentialStoreType::Environment` → reads from `std::env::var`
    /// - `CredentialStoreType::OpenBao` → reads from KV engine via the store
    ///
    /// The `key` field encodes the lookup coordinates:
    /// - Environment: raw env-var name (e.g. `"GMAIL_TOKEN"`)
    /// - OpenBao: `"vault:<namespace>/<mount>/<path>#<field>"` or `"vault:<mount>/<path>"`
    pub async fn resolve_credential(
        &self,
        credential: &CredentialRef,
    ) -> Result<String, SecretsError> {
        match credential.store_type {
            CredentialStoreType::Environment => std::env::var(&credential.key).map_err(|_| {
                SecretsError::CredentialResolutionError(format!(
                    "Environment variable '{}' not set",
                    credential.key
                ))
            }),
            CredentialStoreType::OpenBao => {
                // Parse "vault:engine/path" or "vault:engine/path#field"
                let raw = credential
                    .key
                    .strip_prefix("vault:")
                    .unwrap_or(&credential.key);

                let (kv_path, field) = if let Some((path, f)) = raw.rsplit_once('#') {
                    (path, Some(f))
                } else {
                    (raw, None)
                };

                // Split "engine/rest/of/path"
                let (engine, path) = kv_path.split_once('/').ok_or_else(|| {
                    SecretsError::InvalidPath(format!(
                        "OpenBao credential key must contain at least engine/path: '{}'",
                        raw
                    ))
                })?;

                if let Some(field) = field {
                    self.read_secret_field(engine, path, field).await
                } else {
                    // Return first value when no field specified
                    let secret = self.store.read(engine, path).await?;
                    secret
                        .into_values()
                        .next()
                        .ok_or_else(|| SecretsError::SecretNotFound {
                            path: kv_path.to_string(),
                        })
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mock_manager() -> SecretsManager {
        SecretsManager::from_store(Arc::new(MockSecretStore::new()))
    }

    // -- MockSecretStore KV tests --

    #[tokio::test]
    async fn test_mock_secret_store_read_write() {
        let store = MockSecretStore::new();
        let data = HashMap::from([
            ("api_key".to_string(), "sk-abc123".to_string()),
            ("region".to_string(), "us-east-1".to_string()),
        ]);

        store.write("kv", "openai", data.clone()).await.unwrap();
        let result = store.read("kv", "openai").await.unwrap();
        assert_eq!(result, data);
    }

    #[tokio::test]
    async fn test_mock_secret_store_read_not_found() {
        let store = MockSecretStore::new();
        let result = store.read("kv", "nonexistent").await;
        assert!(matches!(result, Err(SecretsError::SecretNotFound { .. })));
    }

    // -- MockSecretStore Transit tests --

    #[tokio::test]
    async fn test_mock_secret_store_transit_sign_verify() {
        let store = MockSecretStore::new();
        let data = b"agent output payload";
        let signature = store.transit_sign("agent-identity", data).await.unwrap();

        // Valid signature should verify
        let valid = store
            .transit_verify("agent-identity", data, &signature)
            .await
            .unwrap();
        assert!(valid);

        // Tampered data should not verify
        let tampered = store
            .transit_verify("agent-identity", b"tampered", &signature)
            .await
            .unwrap();
        assert!(!tampered);
    }

    #[tokio::test]
    async fn test_mock_secret_store_transit_encrypt_decrypt() {
        let store = MockSecretStore::new();
        let plaintext = b"workflow blackboard state with PII";

        let ciphertext = store
            .transit_encrypt("workflow-state-key", plaintext)
            .await
            .unwrap();

        let decrypted = store
            .transit_decrypt("workflow-state-key", &ciphertext)
            .await
            .unwrap();

        assert_eq!(decrypted, plaintext);
    }

    #[tokio::test]
    async fn test_mock_secret_store_transit_decrypt_wrong_key() {
        let store = MockSecretStore::new();
        let plaintext = b"data";

        let ciphertext = store.transit_encrypt("key-a", plaintext).await.unwrap();

        let result = store.transit_decrypt("key-b", &ciphertext).await;
        assert!(matches!(result, Err(SecretsError::TransitError(_))));
    }

    // -- MockSecretStore Dynamic Secrets tests --

    #[tokio::test]
    async fn test_mock_secret_store_dynamic_secret() {
        let store = MockSecretStore::new();
        let creds = store
            .generate_dynamic("database", "agent-readonly")
            .await
            .unwrap();

        assert!(creds.lease_id.contains("agent-readonly"));
        assert_eq!(creds.lease_duration, Duration::from_secs(300));
        assert!(creds.renewable);
        assert!(creds.data.contains_key("username"));
        assert!(creds.data.contains_key("password"));
    }

    #[tokio::test]
    async fn test_mock_secret_store_lease_lifecycle() {
        let store = MockSecretStore::new();

        // Renew returns the requested increment
        let renewed = store
            .renew_lease("some-lease", Duration::from_secs(600))
            .await
            .unwrap();
        assert_eq!(renewed, Duration::from_secs(600));

        // Revoke succeeds
        store.revoke_lease("some-lease").await.unwrap();
    }

    // -- SecretsManager facade tests --

    #[tokio::test]
    async fn test_secrets_manager_read_secret_field() {
        let manager = mock_manager();
        let data = HashMap::from([
            ("oauth_token".to_string(), "ya29.mock".to_string()),
            ("client_id".to_string(), "123.apps".to_string()),
        ]);

        manager
            .store
            .write("kv", "mcp-tools/gmail", data)
            .await
            .unwrap();

        let token = manager
            .read_secret_field("kv", "mcp-tools/gmail", "oauth_token")
            .await
            .unwrap();
        assert_eq!(token, "ya29.mock");

        // Missing field returns error
        let result = manager
            .read_secret_field("kv", "mcp-tools/gmail", "nonexistent")
            .await;
        assert!(matches!(result, Err(SecretsError::SecretNotFound { .. })));
    }

    #[tokio::test]
    async fn test_secrets_manager_sign_verify() {
        let manager = mock_manager();
        let data = b"code output";

        let sig = manager.sign("agent-identity", data).await.unwrap();
        let valid = manager.verify("agent-identity", data, &sig).await.unwrap();
        assert!(valid);
    }

    #[tokio::test]
    async fn test_secrets_manager_encrypt_decrypt() {
        let manager = mock_manager();
        let plaintext = b"sensitive blackboard data";

        let ct = manager
            .encrypt("workflow-state-key", plaintext)
            .await
            .unwrap();
        let pt = manager.decrypt("workflow-state-key", &ct).await.unwrap();
        assert_eq!(pt, plaintext);
    }

    // -- Credential Resolution tests --

    #[tokio::test]
    async fn test_credential_ref_resolution_env() {
        let manager = mock_manager();
        // Set an env var for test (best-effort; concurrent tests may race)
        std::env::set_var("AEGIS_TEST_SECRET_XYZ", "test-value-123");

        let cred = CredentialRef {
            store_type: CredentialStoreType::Environment,
            key: "AEGIS_TEST_SECRET_XYZ".to_string(),
        };
        let value = manager.resolve_credential(&cred).await.unwrap();
        assert_eq!(value, "test-value-123");

        // Clean up
        std::env::remove_var("AEGIS_TEST_SECRET_XYZ");
    }

    #[tokio::test]
    async fn test_credential_ref_resolution_env_missing() {
        let manager = mock_manager();
        let cred = CredentialRef {
            store_type: CredentialStoreType::Environment,
            key: "AEGIS_NONEXISTENT_VAR_Z9X8".to_string(),
        };
        let result = manager.resolve_credential(&cred).await;
        assert!(matches!(
            result,
            Err(SecretsError::CredentialResolutionError(_))
        ));
    }

    #[tokio::test]
    async fn test_credential_ref_resolution_openbao() {
        let manager = mock_manager();

        // Pre-populate the mock store
        let data = HashMap::from([("oauth_token".to_string(), "ya29.vault-token".to_string())]);
        manager
            .store
            .write("kv", "mcp-tools/gmail", data)
            .await
            .unwrap();

        // Resolve with field specifier
        let cred = CredentialRef {
            store_type: CredentialStoreType::OpenBao,
            key: "vault:kv/mcp-tools/gmail#oauth_token".to_string(),
        };
        let value = manager.resolve_credential(&cred).await.unwrap();
        assert_eq!(value, "ya29.vault-token");
    }

    #[tokio::test]
    async fn test_credential_ref_resolution_openbao_no_field() {
        let manager = mock_manager();

        let data = HashMap::from([("value".to_string(), "single-secret".to_string())]);
        manager
            .store
            .write("kv", "simple/secret", data)
            .await
            .unwrap();

        let cred = CredentialRef {
            store_type: CredentialStoreType::OpenBao,
            key: "vault:kv/simple/secret".to_string(),
        };
        let value = manager.resolve_credential(&cred).await.unwrap();
        assert_eq!(value, "single-secret");
    }

    #[tokio::test]
    async fn test_credential_ref_resolution_openbao_invalid_path() {
        let manager = mock_manager();
        let cred = CredentialRef {
            store_type: CredentialStoreType::OpenBao,
            key: "vault:no-slash-here".to_string(),
        };
        let result = manager.resolve_credential(&cred).await;
        assert!(matches!(result, Err(SecretsError::InvalidPath(_))));
    }
}
